In [ ]:
import pandas as pd
import nltk
from nltk.tokenize import word_tokenize
from nltk.corpus import stopwords
from nltk.stem import WordNetLemmatizer

In [ ]:
df=pd.read_csv('/content/nlp_dataset.csv')
df

                                                Text
0  Natural Language Processing is a fascinating f...
1  It bridges the gap between humans and machines...
2  NLP techniques are widely used in applications...
3  Machine translation and speech recognition are...
4  Despite its advancements, NLP faces challenges...
5  Continuous research and innovation are improvi...
6  The potential of NLP is vast, making it essent...

In [ ]:
nltk.download('punkt')
nltk.download('stopwords')
nltk.download('wordnet')
nltk.download('omw-1.4')
nltk.download('punkt_tab')

[nltk_data] Downloading package punkt to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt.zip.
[nltk_data] Downloading package stopwords to /root/nltk_data...
[nltk_data]   Unzipping corpora/stopwords.zip.
[nltk_data] Downloading package wordnet to /root/nltk_data...
[nltk_data] Downloading package omw-1.4 to /root/nltk_data...
[nltk_data] Downloading package punkt_tab to /root/nltk_data...
[nltk_data]   Unzipping tokenizers/punkt_tab.zip.

True

In [ ]:
stop_words=set(stopwords.words('english'))
print(stop_words)
lematizer=WordNetLemmatizer()

{'don', 'is', 'while', 'up', "weren't", 'why', "we're", 'do', 'through', 'where', "wasn't", 'after', "they'll", 'own', "they've", 'not', 'into', 'what', 'won', 'there', 'above', "they're", 'any', 'than', 'other', 'them', 'this', 'when', 'from', "she'd", "wouldn't", "i'll", "shan't", "she's", 'only', "you'll", 'how', 'yourself', "hasn't", 'm', 'have', "he'd", 'if', "should've", 'they', "it's", 'ain', 'doing', 'further', 'it', 'him', 'are', 'hers', 'here', 'and', "she'll", 'itself', "it'll", 'once', 'my', 'because', 'yourselves', 'an', 'needn', 'these', 'just', 'on', 'their', 'too', "you've", 'wouldn', 'down', 'herself', 'aren', 'you', "you're", "hadn't", 'a', 'again', 'in', 'were', 'couldn', 'against', 'those', 'no', "i'd", 'has', 'll', 'to', 'did', 'she', 'the', 'shan', 'y', "we'd", 'until', 'between', 'does', 're', "you'd", 'hasn', 'isn', 'hadn', 'shouldn', "shouldn't", 'then', 'was', 'very', 'during', 'he', 'its', 'your', "doesn't", "he's", 've', "we've", 'with', 'can', "he'll", 'her', 'mustn', 's', "that'll", "they'd", 'be', 'which', 'now', 'under', 'am', 'about', 'been', 'below', 'mightn', 'being', 'most', "won't", 'at', 'who', 'o', "mightn't", "i've", 'will', 'so', 'should', 'yours', 'or', "we'll", 'his', 'but', 'ours', 'we', 'such', 'didn', 'off', 'ourselves', 'more', 'few', 'having', 'himself', 'both', "needn't", "didn't", 'some', 'had', 'wasn', "couldn't", 'i', 'weren', "aren't", 'before', "isn't", "i'm", 'of', "haven't", 'ma', 'me', 'myself', 'nor', 'that', 'theirs', "it'd", 'out', "mustn't", 'doesn', 'd', 'whom', 'each', 'by', 'for', 'as', 'haven', 'our', 'themselves', 't', 'all', "don't", 'same', 'over'}

In [ ]:
def process_text(text):
  word_tokens=word_tokenize(text)
  filtered_tokens=[word for word in word_tokens if word.lower() not in stop_words] # Corrected 'woed' to 'word' and 'token' to 'word'
  lemmatized_tokens=[lematizer.lemmatize(word.lower()) for word in filtered_tokens] # Added '()' to word.lower
  return{
      'original_text':text,
      'word_tokens':word_tokens,
      'filtered_tokens':filtered_tokens,
      'lemmatized_tokens':lemmatized_tokens
  }

In [ ]:
df['Processed_Text'] = df['Text'].apply(process_text)
df.head()

                                                Text                                     Processed_Text
0  Natural Language Processing is a fascinating f...  {'original_text': 'Natural Language Processing...
1  It bridges the gap between humans and machines...  {'original_text': 'It bridges the gap between ...
2  NLP techniques are widely used in applications...  {'original_text': 'NLP techniques are widely u...
3  Machine translation and speech recognition are...  {'original_text': 'Machine translation and spe...
4  Despite its advancements, NLP faces challenges...  {'original_text': 'Despite its advancements, N...

In [ ]:
results=df["Text"].apply(process_text)


process_df=pd.DataFrame(results.tolist())

print(process_df.head())

processsed_file_path="processed_nlp_dataset.csv"
process_df.to_csv(processsed_file_path,index=False)
print(f"Processed data saved to {processsed_file_path}")

                                       original_text  ...                                  lemmatized_tokens
0  Natural Language Processing is a fascinating f...  ...  [natural, language, processing, fascinating, f...
1  It bridges the gap between humans and machines...  ...  [bridge, gap, human, machine, enabling, comput...
2  NLP techniques are widely used in applications...  ...  [nlp, technique, widely, used, application, ch...
3  Machine translation and speech recognition are...  ...  [machine, translation, speech, recognition, co...
4  Despite its advancements, NLP faces challenges...  ...  [despite, advancement, ,, nlp, face, challenge...

[5 rows x 4 columns]
Processed data saved to processed_nlp_dataset.csv

In [ ]:
results=df['Text'].apply(process_text)
process_df=pd.DataFrame(results.tolist())
print(process_df.head())

                                       original_text  ...                                  lemmatized_tokens
0  Natural Language Processing is a fascinating f...  ...  [natural, language, processing, fascinating, f...
1  It bridges the gap between humans and machines...  ...  [bridge, gap, human, machine, enabling, comput...
2  NLP techniques are widely used in applications...  ...  [nlp, technique, widely, used, application, ch...
3  Machine translation and speech recognition are...  ...  [machine, translation, speech, recognition, co...
4  Despite its advancements, NLP faces challenges...  ...  [despite, advancement, ,, nlp, face, challenge...

[5 rows x 4 columns]